### ISSUE TITLE
please describe login flow

### ISSUE THREAD

**Issue by ashishbindal93** [nodef/extra-fyers#2]
please share code how to login from scratch. How to do login step1 then login step 2 then init new api instance.

**Comment by wolfram77** [comment]
@ashishbindal93 Login requires having a server, so you can recieve a redirect. The [process](https://myapi.fyers.in/docs/#tag/Authentication-and-Login-Flow-User-Apps) is as follows:

1. Make a `GET` request to the URL obtained from `loginStep1()`.
2. You will recieve `GET` request with `auth_code` on your *redirect URL*.
3. Now make a `POST` request to the URL (with data) from `loginStep2()`.
4. You will get `access_token` in the response.

You can host your server, for example in [glitch](https://glitch.com), or for the time being, use [my site](https://extra-fyers.glitch.me/login) to login, with *redirect URL* `https://extra-fyers.glitch.me/callback/test-login`.

**Comment by ashishbindal93** [comment]
okay, thanks. I got it. I have to make requests.
