### ISSUE TITLE
For F&O data is null

### ISSUE THREAD

**Issue by shyamg2000** [nodef/extra-fyers#4]
Getting null data for F&O, Index are fine. Till friday it was working fine.
following is the data
 {                                   
   symbol: 'NSE:INDIAVIX-INDEX',     
   token: '101000000026017',         
   name: 'INDIAVIX-INDEX',           
   exchange: 'NSE',                  
   description: 'NSE:INDIAVIX-INDEX',
   priceChange: -0.7,                
   priceChangePercent: -5.25,        
   currentPrice: 12.63,              
   priceSpread: 0,                   
   askPrice: 0,                      
   bidPrice: 0,                      
   openPrice: 13.33,                 
   highPrice: 13.4675,               
   lowPrice: 12.4875,                
   closePrice: 13.33,                
   volume: 0,                        
   date: 1704672000,                 
   candle: null                      
 },                                  
 {                                   
   symbol: 'NSE:BANKNIFTY24JANFUT',  
   token: undefined,                 
   name: undefined,                  
   exchange: undefined,              
   description: undefined,           
   priceChange: undefined,           
   priceChangePercent: undefined,    
   currentPrice: undefined,          
   priceSpread: undefined,           
   askPrice: undefined,              
   bidPrice: undefined,              
   openPrice: undefined,             
   highPrice: undefined,             
   lowPrice: undefined,              
   closePrice: undefined,            
   volume: undefined,                
   date: undefined,                  
   candle: null                      
 },

**Comment by shyamg2000** [comment]
The same issue is faced with getMarketQuotes also.

**Comment by shyamg2000** [comment]
After debuging your code, I realised that there is some issue with response that we get from fyers only for F&O, for index the response is correct. below is the response fro NiftyFutures

{
n: 'NSE:NIFTY24JANFUT',
s: 'ok',
v: { s: 'error', n: 'NSE:NIFTY24JANFUT', code: -17, errmsg: '' }
}

**Comment by wolfram77** [comment]
An `ok` status encapsulating an `error` status - this is good engineering. If i check error `-17`, it seems to say

```csv
...
-371,Invalid SHA256 hash of (app_id:secret_key)
-17,Invalid access token used for authentication
-352,Invalid app id
...
```

I am not sure if this is correct.

Do you now need to enable so additional permissions to work with futures? Maybe due to recent regulations?

**Comment by shyamg2000** [comment]
Very strange, today its all working fine.
I guess fyers have revered the code changes

**Comment by wolfram77** [comment]
Cool
